// GALLERY
export const CREATE_GALLERY_DONE       = 'CREATE_GALLERY_DONE';
export const CREATE_GALLERY_START      = 'CREATE_GALLERY_START';
export const CREATE_GALLERY_ERROR      = 'CREATE_GALLERY_ERROR';
export const UPDATE_GALLERY_DONE       = 'UPDATE_GALLERY_DONE';
export const UPDATE_GALLERY_START      = 'UPDATE_GALLERY_START';
export const UPDATE_GALLERY_ERROR      = 'UPDATE_GALLERY_ERROR';
export const DELETE_GALLERY_DONE       = 'DELETE_GALLERY_DONE';
export const DELETE_GALLERY_START      = 'DELETE_GALLERY_START';
export const DELETE_GALLERY_ERROR      = 'DELETE_GALLERY_ERROR';
export const FETCH_ALL_GALLERIES_DONE  = 'FETCH_ALL_GALLERIES_DONE';
export const FETCH_ALL_GALLERIES_START = 'FETCH_ALL_GALLERIES_START';
export const FETCH_ALL_GALLERIES_ERROR = 'FETCH_ALL_GALLERIES_ERROR';
export const SEARCH_GALLERIES_DONE     = 'SEARCH_GALLERIES_DONE';
export const SEARCH_GALLERIES_START    = 'SEARCH_GALLERIES_START';
export const SEARCH_GALLERIES_ERROR    = 'SEARCH_GALLERIES_ERROR';
export const SEARCH_GALLERIES_RESET    = 'SEARCH_GALLERIES_RESET';

// PICTURES
export const FETCH_ALL_PICTURES_DONE  = 'FETCH_ALL_PICTURES_DONE';
export const FETCH_ALL_PICTURES_START = 'FETCH_ALL_PICTURES_START';
export const FETCH_ALL_PICTURES_ERROR = 'FETCH_ALL_PICTURES_ERROR';
export const CREATE_PICTURE_DONE      = 'CREATE_PICTURE_DONE';
export const CREATE_PICTURE_START     = 'CREATE_PICTURE_START';
export const CREATE_PICTURE_ERROR     = 'CREATE_PICTURE_ERROR';
export const UPDATE_PICTURE_DONE      = 'UPDATE_PICTURE_DONE';
export const UPDATE_PICTURE_START     = 'UPDATE_PICTURE_START';
export const UPDATE_PICTURE_ERROR     = 'UPDATE_PICTURE_ERROR';
export const DELETE_PICTURE_DONE      = 'DELETE_PICTURE_DONE';
export const DELETE_PICTURE_START     = 'DELETE_PICTURE_START';
export const DELETE_PICTURE_ERROR     = 'DELETE_PICTURE_ERROR';

// AUTH
export const AUTH_START = 'AUTH_START ';
export const AUTH_DONE  = 'AUTH_DONE ';
export const AUTH_ERROR = 'AUTH_ERROR ';
export const LOGOUT     = 'LOGOUT';

// TODO
export const LIKE = 'LIKE';
