// GALLERY
export const CREATE_GALLERY_DONE       = 'CREATE_GALLERY_DONE';
export const CREATE_GALLERY_START      = 'CREATE_GALLERY_START';
export const CREATE_GALLERY_ERROR      = 'CREATE_GALLERY_ERROR';
export const UPDATE_GALLERY_DONE       = 'UPDATE_GALLERY_DONE';
export const UPDATE_GALLERY_START      = 'UPDATE_GALLERY_START';
export const UPDATE_GALLERY_ERROR      = 'UPDATE_GALLERY_ERROR';
export const DELETE_GALLERY_DONE       = 'DELETE_GALLERY_DONE';
export const DELETE_GALLERY_START      = 'DELETE_GALLERY_START';
export const DELETE_GALLERY_ERROR      = 'DELETE_GALLERY_ERROR';
export const FETCH_ALL_GALLERIES_DONE  = 'FETCH_ALL_GALLERIES_DONE';
export const FETCH_ALL_GALLERIES_START = 'FETCH_ALL_GALLERIES_START';
export const FETCH_ALL_GALLERIES_ERROR = 'FETCH_ALL_GALLERIES_ERROR';

// AUTH
export const AUTH_START = 'AUTH_START ';
export const AUTH_DONE  = 'AUTH_DONE ';
export const AUTH_ERROR = 'AUTH_ERROR ';
export const LOGOUT     = 'LOGOUT';

// TODO
export const LIKE = 'LIKE';
